export const INITIAL_USER = {
  id: 'usr_001',
  name: 'Shani Kakadiya',
  email: 'shani.kakadiya@daiict.ac.in',
  phone: '+91 98765 43210',
  state: 'Gujarat',
  city: 'Gandhinagar',
  latitude: 23.1884,
  longitude: 72.6289,
  locationSource: 'GPS Auto-detected',
  role: 'driver', // 'driver' | 'operator'
  companyName: 'Tata Power',
  savedStations: ['st_01', 'st_03', 'st_07'],
  priceAlertThreshold: 7.00,
  greenGoal: 85,
  stats: {
    totalSessions: 38,
    totalEnergyCharged: 942.5, // kWh
    totalSavedInr: 4320,
    totalCo2AvoidedKg: 684.2,
    overallGreenScore: 92
  }
};

export const INITIAL_VEHICLES = [
  {
    id: 'veh_01',
    name: 'Nexon EV Long Range',
    nickname: 'Stealth Green',
    type: 'SUV',
    brand: 'Tata',
    model: 'Nexon EV Empowered+',
    batteryCapacity: 40.5,
    currentBatteryPct: 68,
    targetBatteryPct: 85,
    connector: 'CCS2',
    maxChargingPower: 50,
    standardRange: 453,
    currentRangeEstimate: 308,
    greenScore: 94,
    healthScore: 98,
    efficiency: '132 Wh/km',
    isPrimary: true
  },
  {
    id: 'veh_02',
    name: 'Ather 450X',
    nickname: 'City Dart',
    type: 'Scooter',
    brand: 'Ather',
    model: '450X Gen 3',
    batteryCapacity: 3.7,
    currentBatteryPct: 84,
    targetBatteryPct: 100,
    connector: 'Type 2',
    maxChargingPower: 3.3,
    standardRange: 150,
    currentRangeEstimate: 126,
    greenScore: 96,
    healthScore: 99,
    efficiency: '32 Wh/km',
    isPrimary: false
  },
  {
    id: 'veh_03',
    name: 'MG ZS EV',
    nickname: 'Family Cruiser',
    type: 'SUV',
    brand: 'MG',
    model: 'ZS EV Exclusive Plus',
    batteryCapacity: 50.3,
    currentBatteryPct: 32,
    targetBatteryPct: 80,
    connector: 'CCS2',
    maxChargingPower: 60,
    standardRange: 461,
    currentRangeEstimate: 148,
    greenScore: 89,
    healthScore: 96,
    efficiency: '145 Wh/km',
    isPrimary: false
  }
];

export const HOURLY_GRID_DATA = [
  { time: '00:00', price: 7.80, solar: 0, wind: 35, hydro: 18, coal: 38, gas: 9, gridDemand: 42, greenScore: 78, status: 'GOOD' },
  { time: '02:00', price: 7.20, solar: 0, wind: 42, hydro: 20, coal: 32, gas: 6, gridDemand: 36, greenScore: 82, status: 'GOOD' },
  { time: '04:00', price: 6.90, solar: 0, wind: 48, hydro: 22, coal: 25, gas: 5, gridDemand: 32, greenScore: 86, status: 'CHEAP' },
  { time: '06:00', price: 7.40, solar: 10, wind: 38, hydro: 20, coal: 27, gas: 5, gridDemand: 45, greenScore: 84, status: 'GOOD' },
  { time: '08:00', price: 8.60, solar: 32, wind: 24, hydro: 15, coal: 24, gas: 5, gridDemand: 68, greenScore: 85, status: 'NORMAL' },
  { time: '10:00', price: 7.60, solar: 54, wind: 20, hydro: 12, coal: 10, gas: 4, gridDemand: 58, greenScore: 91, status: 'GOOD' },
  { time: '12:00', price: 6.40, solar: 68, wind: 18, hydro: 8, coal: 4, gas: 2, gridDemand: 44, greenScore: 96, status: 'CHEAP' },
  { time: '13:00', price: 6.20, solar: 72, wind: 17, hydro: 7, coal: 2, gas: 2, gridDemand: 40, greenScore: 98, status: 'CHEAP' },
  { time: '14:00', price: 6.50, solar: 69, wind: 20, hydro: 7, coal: 3, gas: 1, gridDemand: 45, greenScore: 95, status: 'CHEAP' },
  { time: '16:00', price: 7.10, solar: 45, wind: 22, hydro: 12, coal: 16, gas: 5, gridDemand: 56, greenScore: 88, status: 'GOOD' },
  { time: '18:00', price: 9.80, solar: 12, wind: 20, hydro: 18, coal: 42, gas: 8, gridDemand: 82, greenScore: 68, status: 'NORMAL' },
  { time: '19:00', price: 11.40, solar: 0, wind: 18, hydro: 16, coal: 55, gas: 11, gridDemand: 94, greenScore: 54, status: 'EXPENSIVE' },
  { time: '20:00', price: 11.90, solar: 0, wind: 16, hydro: 15, coal: 58, gas: 11, gridDemand: 96, greenScore: 50, status: 'EXPENSIVE' },
  { time: '21:00', price: 10.50, solar: 0, wind: 22, hydro: 18, coal: 50, gas: 10, gridDemand: 85, greenScore: 60, status: 'EXPENSIVE' },
  { time: '22:00', price: 8.90, solar: 0, wind: 30, hydro: 20, coal: 42, gas: 8, gridDemand: 65, greenScore: 72, status: 'NORMAL' },
  { time: '23:00', price: 8.10, solar: 0, wind: 34, hydro: 20, coal: 38, gas: 8, gridDemand: 52, greenScore: 76, status: 'GOOD' }
];

export const CURRENT_LIVE_METRICS = {
  pricePerKwh: 8.40,
  priceType: 'Estimated charging price', // 'Actual station price' | 'Estimated charging price' | 'Demo price'
  isDemo: false,
  status: 'GOOD',
  greenScore: 87,
  gridDemand: 48,
  breakdown: {
    baseEnergyCost: 7.50,
    solarBenefit: -0.60,
    windBenefit: -0.20,
    gridDemandAdjustment: 0.50,
    thermalGenerationAdj: 0.70,
    stationNetworkFee: 0.50,
    estimatedPrice: 8.40
  },
  energyMix: {
    solar: 52,
    wind: 18,
    hydro: 10,
    coal: 16,
    gas: 4,
    other: 0,
    totalRenewable: 80
  },
  aiRecommendation: {
    title: 'Optimal Window Coming Up',
    actionText: 'Wait 1 hour 15 minutes',
    targetTimeWindow: '1:00 PM – 3:30 PM',
    expectedPrice: 6.80,
    renewablePct: 89,
    estimatedSavingInr: 48,
    greenScore: 94,
    confidence: 'High',
    confidenceScore: 96,
    reasoning: 'Massive solar injection into Western Grid peak reduces tariff by ₹1.60/kWh with 89% green mix.'
  },
  smartChargingWindow: {
    bestWindow: '2:00 PM – 4:00 PM',
    bestPrice: 6.50,
    bestRenewable: 89,
    bestGreenScore: 94,
    saving: 72,
    worstWindow: '7:00 PM – 9:00 PM',
    worstPrice: 11.40,
    worstReason: 'High grid peak demand + 58% coal thermal dispatch'
  }
};

export const STATIONS_DATA = [
  {
    id: 'st_01',
    name: 'GreenHub Solar Supercharger',
    network: 'Tata Power',
    networkId: 'tata-power',
    address: 'Infocity Circle, DAIICT Road, Gandhinagar',
    city: 'Gandhinagar',
    state: 'Gujarat',
    lat: 23.1878,
    lng: 72.6275,
    distanceKm: 0.8,
    availableChargers: 4,
    totalChargers: 6,
    powerKw: 60,
    speedLabel: 'Fast DC (60 kW)',
    connectors: ['CCS2', 'Type 2', 'Bharat AC001'],
    pricePerKwh: 8.40,
    priceType: 'Actual station price',
    greenScore: 92,
    renewablePct: 90,
    isHospitalNearby: true,
    nearbyHospital: 'Apollo Hospitals Gandhinagar (450m)',
    isFast: true,
    isAvailable: true,
    isLowCost: false,
    isGreen: true,
    rating: 4.8,
    reviewsCount: 142,
    amenities: ['Café & Snacks', 'Restrooms', '24/7 Security', 'Free High-speed WiFi', 'AC Lounge'],
    openingStatus: 'Open 24/7',
    lastUpdated: '2 mins ago',
    peakHours: '6 PM - 9 PM',
    coordinates: { x: 42, y: 38 } // Visual map representation coordinates
  },
  {
    id: 'st_02',
    name: 'Jio-bp pulse Express Hub',
    network: 'Jio-bp',
    networkId: 'jio-bp',
    address: 'SG Highway, Opp. Iscon Mega Mall, Ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0305,
    lng: 72.5074,
    distanceKm: 4.2,
    availableChargers: 6,
    totalChargers: 8,
    powerKw: 120,
    speedLabel: 'Ultra-Fast DC (120 kW)',
    connectors: ['CCS2', 'Type 2'],
    pricePerKwh: 7.80,
    priceType: 'Actual station price',
    greenScore: 88,
    renewablePct: 78,
    isHospitalNearby: true,
    nearbyHospital: 'Zydus Hospital SG Highway (800m)',
    isFast: true,
    isAvailable: true,
    isLowCost: true,
    isGreen: true,
    rating: 4.7,
    reviewsCount: 298,
    amenities: ['Wild Bean Café', 'Clean Restrooms', 'Air-water Station', '24/7 Security'],
    openingStatus: 'Open 24/7',
    lastUpdated: 'Just now',
    peakHours: '7 PM - 10 PM',
    coordinates: { x: 28, y: 55 }
  },
  {
    id: 'st_03',
    name: 'ChargeZone Wind & Sun Station',
    network: 'ChargeZone',
    networkId: 'chargezone',
    address: 'GIFT City SEZ Boulevard, Gandhinagar',
    city: 'Gandhinagar',
    state: 'Gujarat',
    lat: 23.1601,
    lng: 72.6841,
    distanceKm: 5.6,
    availableChargers: 5,
    totalChargers: 6,
    powerKw: 150,
    speedLabel: 'Hyper Fast DC (150 kW)',
    connectors: ['CCS2', 'Type 2', 'GB/T'],
    pricePerKwh: 6.80,
    priceType: 'Estimated charging price',
    greenScore: 96,
    renewablePct: 94,
    isHospitalNearby: false,
    nearbyHospital: null,
    isFast: true,
    isAvailable: true,
    isLowCost: true,
    isGreen: true,
    rating: 4.9,
    reviewsCount: 88,
    amenities: ['Smart Parking', 'Starbucks nearby', 'Restrooms', 'CCTV'],
    openingStatus: 'Open 24/7',
    lastUpdated: '1 min ago',
    peakHours: '1 PM - 4 PM (Cheapest Window)',
    coordinates: { x: 70, y: 32 }
  },
  {
    id: 'st_04',
    name: 'Statiq EcoPower Bay',
    network: 'Statiq',
    networkId: 'statiq',
    address: 'Prahlad Nagar Corporate Road, Ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0112,
    lng: 72.5123,
    distanceKm: 6.1,
    availableChargers: 2,
    totalChargers: 4,
    powerKw: 50,
    speedLabel: 'Fast DC (50 kW)',
    connectors: ['CCS2', 'Type 2'],
    pricePerKwh: 9.20,
    priceType: 'Actual station price',
    greenScore: 78,
    renewablePct: 65,
    isHospitalNearby: true,
    nearbyHospital: 'Shalby Multi-specialty Hospital (650m)',
    isFast: true,
    isAvailable: true,
    isLowCost: false,
    isGreen: false,
    rating: 4.4,
    reviewsCount: 165,
    amenities: ['Food Court', 'Basement Parking', 'Security Guard'],
    openingStatus: 'Closes at 11:30 PM',
    lastUpdated: '5 mins ago',
    peakHours: '6 PM - 9 PM',
    coordinates: { x: 35, y: 68 }
  },
  {
    id: 'st_05',
    name: 'Zeon Electric Fast Charging',
    network: 'Zeon',
    networkId: 'zeon',
    address: 'Ahmedabad - Vadodara Expressway Plaza',
    city: 'Ahmedabad',
    state: 'Gujarat',
    lat: 22.9812,
    lng: 72.6312,
    distanceKm: 9.4,
    availableChargers: 3,
    totalChargers: 4,
    powerKw: 60,
    speedLabel: 'Fast DC (60 kW)',
    connectors: ['CCS2'],
    pricePerKwh: 8.90,
    priceType: 'Actual station price',
    greenScore: 82,
    renewablePct: 72,
    isHospitalNearby: false,
    nearbyHospital: null,
    isFast: true,
    isAvailable: true,
    isLowCost: false,
    isGreen: true,
    rating: 4.6,
    reviewsCount: 112,
    amenities: ['Highway Diner', 'Clean Washrooms', '24/7 Service'],
    openingStatus: 'Open 24/7',
    lastUpdated: '4 mins ago',
    peakHours: '8 AM - 11 AM',
    coordinates: { x: 62, y: 76 }
  },
  {
    id: 'st_06',
    name: 'HPCL EV Green Corridor Point',
    network: 'HPCL',
    networkId: 'hpcl',
    address: 'Koba Highway Circle, Gandhinagar',
    city: 'Gandhinagar',
    state: 'Gujarat',
    lat: 23.1412,
    lng: 72.6345,
    distanceKm: 2.9,
    availableChargers: 1,
    totalChargers: 2,
    powerKw: 30,
    speedLabel: 'DC Fast (30 kW)',
    connectors: ['CCS2', 'Bharat AC001', '15A Socket'],
    pricePerKwh: 7.20,
    priceType: 'Actual station price',
    greenScore: 86,
    renewablePct: 81,
    isHospitalNearby: true,
    nearbyHospital: 'Civil Hospital Gandhinagar (1.2km)',
    isFast: false,
    isAvailable: true,
    isLowCost: true,
    isGreen: true,
    rating: 4.3,
    reviewsCount: 74,
    amenities: ['Petrol Pump convenience store', 'Restroom', 'Tyre Pressure'],
    openingStatus: 'Open 24/7',
    lastUpdated: '3 mins ago',
    peakHours: '5 PM - 8 PM',
    coordinates: { x: 50, y: 48 }
  },
  {
    id: 'st_07',
    name: 'IOCL CleanEnergy Hub',
    network: 'IOCL',
    networkId: 'iocl',
    address: 'Sector 21 Market Ring Road, Gandhinagar',
    city: 'Gandhinagar',
    state: 'Gujarat',
    lat: 23.2201,
    lng: 72.6512,
    distanceKm: 3.5,
    availableChargers: 0,
    totalChargers: 4,
    powerKw: 50,
    speedLabel: 'Fast DC (50 kW)',
    connectors: ['CCS2', 'Type 2'],
    pricePerKwh: 7.50,
    priceType: 'Estimated charging price',
    greenScore: 84,
    renewablePct: 75,
    isHospitalNearby: false,
    nearbyHospital: null,
    isFast: true,
    isAvailable: false,
    isLowCost: true,
    isGreen: true,
    rating: 4.1,
    reviewsCount: 63,
    amenities: ['Store', 'Restroom'],
    openingStatus: 'Open 24/7 (All bays busy)',
    lastUpdated: 'Just now',
    peakHours: 'Busy now',
    coordinates: { x: 58, y: 18 }
  },
  {
    id: 'st_08',
    name: 'BPCL eDrive Solar Hub',
    network: 'BPCL',
    networkId: 'bpcl',
    address: 'Near Motera Stadium, Sabarmati, Ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0912,
    lng: 72.5987,
    distanceKm: 5.1,
    availableChargers: 4,
    totalChargers: 4,
    powerKw: 60,
    speedLabel: 'Fast DC (60 kW)',
    connectors: ['CCS2', 'Type 2'],
    pricePerKwh: 6.90,
    priceType: 'Actual station price',
    greenScore: 93,
    renewablePct: 91,
    isHospitalNearby: true,
    nearbyHospital: 'SMS Multispeciality Hospital (500m)',
    isFast: true,
    isAvailable: true,
    isLowCost: true,
    isGreen: true,
    rating: 4.8,
    reviewsCount: 184,
    amenities: ['Solar Canopy', 'Café', 'Restroom', 'Free WiFi'],
    openingStatus: 'Open 24/7',
    lastUpdated: '2 mins ago',
    peakHours: '2 PM - 5 PM',
    coordinates: { x: 48, y: 62 }
  }
];

export const HOSPITALS_DATA = [
  { id: 'hosp_01', name: 'Apollo Hospitals Gandhinagar', type: 'Multispeciality Hospital', lat: 23.1852, lng: 72.6310, distanceKm: 0.5, coordinates: { x: 44, y: 35 } },
  { id: 'hosp_02', name: 'Zydus Hospital SG Highway', type: 'Super Speciality Hospital', lat: 23.0335, lng: 72.5100, distanceKm: 4.0, coordinates: { x: 26, y: 52 } },
  { id: 'hosp_03', name: 'Shalby Hospitals Prahladnagar', type: 'Orthopaedic & Multi-care', lat: 23.0098, lng: 72.5140, distanceKm: 6.0, coordinates: { x: 37, y: 66 } },
  { id: 'hosp_04', name: 'Civil Hospital Gandhinagar', type: 'Government Medical College Hospital', lat: 23.1430, lng: 72.6320, distanceKm: 2.8, coordinates: { x: 52, y: 46 } }
];

export const PAST_SESSIONS = [
  {
    id: 'ses_101',
    stationId: 'st_01',
    stationName: 'GreenHub Solar Supercharger',
    network: 'Tata Power',
    date: '2026-09-12T09:15:00.000Z',
    energyDeliveredKwh: 24.5,
    durationMinutes: 34,
    pricePerKwh: 6.80,
    totalCostInr: 166.60,
    renewablePct: 92,
    greenScore: 94,
    co2AvoidedKg: 18.5,
    startBatteryPct: 28,
    endBatteryPct: 88,
    vehicleName: 'Nexon EV Long Range'
  },
  {
    id: 'ses_102',
    stationId: 'st_02',
    stationName: 'Jio-bp pulse Express Hub',
    network: 'Jio-bp',
    date: '2026-09-08T14:20:00.000Z',
    energyDeliveredKwh: 31.2,
    durationMinutes: 28,
    pricePerKwh: 7.80,
    totalCostInr: 243.36,
    renewablePct: 84,
    greenScore: 88,
    co2AvoidedKg: 21.4,
    startBatteryPct: 15,
    endBatteryPct: 85,
    vehicleName: 'Nexon EV Long Range'
  },
  {
    id: 'ses_103',
    stationId: 'st_03',
    stationName: 'ChargeZone Wind & Sun Station',
    network: 'ChargeZone',
    date: '2026-09-03T13:05:00.000Z',
    energyDeliveredKwh: 18.0,
    durationMinutes: 18,
    pricePerKwh: 6.80,
    totalCostInr: 122.40,
    renewablePct: 95,
    greenScore: 97,
    co2AvoidedKg: 14.0,
    startBatteryPct: 45,
    endBatteryPct: 90,
    vehicleName: 'Nexon EV Long Range'
  },
  {
    id: 'ses_104',
    stationId: 'st_08',
    stationName: 'BPCL eDrive Solar Hub',
    network: 'BPCL',
    date: '2026-08-28T16:40:00.000Z',
    energyDeliveredKwh: 2.8,
    durationMinutes: 45,
    pricePerKwh: 6.90,
    totalCostInr: 19.32,
    renewablePct: 88,
    greenScore: 91,
    co2AvoidedKg: 2.0,
    startBatteryPct: 20,
    endBatteryPct: 95,
    vehicleName: 'Ather 450X'
  }
];

export const NOTIFICATIONS_DATA = [
  {
    id: 'notif_01',
    type: 'price_drop',
    title: 'Price Drop Alert ⚡',
    message: 'Grid tariff dropped to ₹6.20/kWh due to heavy solar injection in Western grid. Perfect time to top-up!',
    time: '25 mins ago',
    read: false,
    tag: 'amber',
    actionRoute: '/dashboard'
  },
  {
    id: 'notif_02',
    type: 'best_time',
    title: 'Smart Charge Window Open 🟢',
    message: 'High renewable availability (89% solar+wind) from 1:00 PM to 4:00 PM. Estimated savings: ₹72.',
    time: '2 hours ago',
    read: false,
    tag: 'green',
    actionRoute: '/dashboard'
  },
  {
    id: 'notif_03',
    type: 'booking',
    title: 'Slot Reserved Successfully 🚗',
    message: 'Bay #2 at GreenHub Solar Supercharger is locked for your Nexon EV.',
    time: 'Yesterday',
    read: true,
    tag: 'sky',
    actionRoute: '/charging/st_01'
  }
];

export const OPERATOR_DATA = {
  stationName: 'GreenHub Solar Supercharger',
  totalSessionsToday: 38,
  totalRevenueToday: 8420,
  activeChargers: 4,
  totalChargers: 6,
  renewablePct: 90,
  gridCo2Intensity: '142 g/kWh (Clean)',
  uptime: '99.8%',
  weeklyTrend: [
    { day: 'Mon', sessions: 28, revenue: 5800 },
    { day: 'Tue', sessions: 34, revenue: 7200 },
    { day: 'Wed', sessions: 31, revenue: 6900 },
    { day: 'Thu', sessions: 42, revenue: 9100 },
    { day: 'Fri', sessions: 48, revenue: 10400 },
    { day: 'Sat', sessions: 52, revenue: 11800 },
    { day: 'Sun', sessions: 38, revenue: 8420 }
  ]
};
